### ISSUE TITLE
Upgrade to Halogen 5.0.0-rc.4

### ISSUE THREAD

**Issue by rintcius** [MonoidMusician/purescript-halogen-zuruzuru#2]
The branch https://github.com/MonoidMusician/purescript-halogen-zuruzuru/tree/halogen-5 does not incorporate the latest halogen changes yet and is incompatible. 

Are there any plans to update the `halogen-5` branch? If not then I can also have a look in making it uptodate.

**Comment by MonoidMusician** [comment]
Hi @rintcius! Sorry, I just saw this – I've been away for a while, but today I did indeed update it for the latest RC! Thanks for the interest, let me know if you need anything more.

**Comment by rintcius** [comment]
Ah great, thank you!
